//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAjaxTest002
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPOT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEPOT()
        {
            this.STOCKERs = new HashSet<STOCKER>();
        }
    
        public int NUMDEP { get; set; }
        public string NOMDEP { get; set; }
        public string ADRDEP { get; set; }
        public string CPDEP { get; set; }
        public string VILLEDEP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCKER> STOCKERs { get; set; }
    }
}
