//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAjaxTest002
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDITEUR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EDITEUR()
        {
            this.OUVRAGEs = new HashSet<OUVRAGE>();
        }
    
        public string NOMED { get; set; }
        public string ADRED { get; set; }
        public string CPED { get; set; }
        public string VILLEED { get; set; }
        public string TELED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OUVRAGE> OUVRAGEs { get; set; }
    }
}
