//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAjaxTest002
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class librairieEntities : DbContext
    {
        public librairieEntities()
            : base("name=librairieEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CATALOGUE> CATALOGUEs { get; set; }
        public virtual DbSet<CLASSIFICATION> CLASSIFICATIONs { get; set; }
        public virtual DbSet<DEPOT> DEPOTs { get; set; }
        public virtual DbSet<ECRIVAIN> ECRIVAINs { get; set; }
        public virtual DbSet<EDITEUR> EDITEURs { get; set; }
        public virtual DbSet<OUVRAGE> OUVRAGEs { get; set; }
        public virtual DbSet<STOCKER> STOCKERs { get; set; }
        public virtual DbSet<TARIFER> TARIFERs { get; set; }
    }
}
