//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAjaxTest002
{
    using System;
    using System.Collections.Generic;
    
    public partial class OUVRAGE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OUVRAGE()
        {
            this.STOCKERs = new HashSet<STOCKER>();
            this.TARIFERs = new HashSet<TARIFER>();
            this.ECRIVAINs = new HashSet<ECRIVAIN>();
        }
    
        public int NUMOUVR { get; set; }
        public string NOMOUVR { get; set; }
        public Nullable<short> ANNEEPARU { get; set; }
        public Nullable<int> NUMRUB { get; set; }
        public string NOMED { get; set; }
    
        public virtual CLASSIFICATION CLASSIFICATION { get; set; }
        public virtual EDITEUR EDITEUR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCKER> STOCKERs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TARIFER> TARIFERs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ECRIVAIN> ECRIVAINs { get; set; }
    }
}
